'use client';
import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import { Provider } from "react-redux";
import { store } from "./store/store";

// export const metadata = {
//   title: "EmkiProd",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
         <Provider store={store}>
          <Navbar />
         <main className="relative overflow-hidden">{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
